### ISSUE TITLE
How to install TiPagingControl ?

### ISSUE THREAD

**Issue by clem983** [deckameron/TiPagingControl#1]
Hi, 
I begin with Titanium and I want to install TiPagingControl. But when I add it with "install mobile module", it doesn't appear in TiApp Editor. I tried to simply put it in a folder, but he is not found by the "require" in my JS files.
Can you help me, please ?

Thanks a lot :)

**Comment by deckameron** [comment]
Hi @clem983!

PagingControl is not a module. It is a JS file just like the ones you create on your project. :-)

Lets try this:
- create a folder called "services" in your Resources folder
- copy PagingControl inside the services folder you have just created
- call the PagingControl like this: `var pagingControl = require("/services/PagingControl/widget");`

You folder structure should be like this:
Resources -
                   | services -
                                    | PagingControl

Let me know if this helps!

**Comment by clem983** [comment]
Hi @deckameron 
It works ! I tried this stuff but probably forgot some details ... !
Thanks a lot for your help and for the speed of your response :)

**Comment by deckameron** [comment]
Hi @clem983 
I am happy to help! :)
